import './globals.css';
import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Footer } from '@/component/Footer';
import { Header } from '@/component/Header';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Footer></Footer>
        {children}
        <Header></Header>
      </body>
    </html>
  );
}
